language: java
postgres:
  adapter: postgresql
  database: app
  username: postgres
env:
  - DATABASE_URL=postgres://app:@localhost/postgres
before_script:
  - "psql -c 'create database app;' -U postgres
